EddieHubCommunity/good-first-issue-finder

.gitpod.yml, package-lock.json, package.json, request.http, src/hooks.ts, src/routes/api/login.ts, src/routes/auth.svelte, src/routes/index.svelte, svelte.config.js
=> Add Authentication

.gitpod.yml
closes #3
<a href="https://gitpod.io/#https://github.com/Cahllagerfeld/issue-crawler/pull/5"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Prebuild for Gitpod

src/lib/stores/user.store.ts, src/routes/__layout.svelte, src/routes/api/login.ts, src/routes/auth.svelte
closes #8 
<a href="https://gitpod.io/#https://github.com/Cahllagerfeld/issue-crawler/pull/9"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add user request

src/routes/auth.svelte, src/routes/index.svelte
closes #1
<a href="https://gitpod.io/#https://github.com/Cahllagerfeld/issue-crawler/pull/10"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Query Github Api

src/app.css, src/lib/components/card.svelte, src/lib/components/issue-card.svelte, src/lib/types/github.type.ts, src/routes/__layout.svelte, src/routes/auth.svelte, src/routes/index.svelte, tailwind.config.cjs
closes #12
<a href="https://gitpod.io/#https://github.com/Cahllagerfeld/issue-crawler/pull/13"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Card Component

src/lib/components/nav.svelte
closes #17
<a href="https://gitpod.io/#https://github.com/Cahllagerfeld/issue-crawler/pull/19"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add backlink to nav

src/lib/components/button.svelte, src/lib/components/nav.svelte, src/lib/types/button.type.ts, tailwind.config.cjs
closes #7
<a href="https://gitpod.io/#https://github.com/Cahllagerfeld/issue-crawler/pull/21"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Button Component

src/lib/components/nav.svelte, src/routes/logout.ts
closes #18
<a href="https://gitpod.io/#https://github.com/Cahllagerfeld/issue-crawler/pull/22"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Sign-Out

dockerfile, package-lock.json, package.json, svelte.config.js
closes #23
<a href="https://gitpod.io/#https://github.com/Cahllagerfeld/issue-crawler/pull/24"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Dockerize Application

package-lock.json, package.json
=> Pin Sveltekit Version

.github/workflows/deploy.yml, .github/workflows/release.yml, kubernetes/deployment.yaml, kubernetes/ingress.yaml, kubernetes/service.yaml
=> feat: release, docker, deploy (#32)

kubernetes/deployment.yaml, kubernetes/ingress.yaml, kubernetes/service.yaml
fixes the port of deployment
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/39"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: deployment port

CHANGELOG.md, package-lock.json, package.json, src/lib/components/issue-card.svelte, src/lib/types/github.types.ts, src/routes/api/get-issues.ts, src/routes/index.svelte
closese #46
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/48"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Switch to GraphQL

.github/workflows/labels.yml
Closing #47
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/50"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added the label action workflow

src/lib/components/footer.svelte, src/routes/__layout.svelte
closes #45
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/67"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add footer

CODE_OF_CONDUCT.md
**I have added the CODE_OF_CONDUCT file via this PR. 
This closes #84 .**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/85"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add CODE_OF_CONDUCT.md

package-lock.json, src/lib/components/issue-card.svelte, src/lib/components/toggle.svelte, src/routes/api/get-issues.ts, src/routes/index.svelte
closes #25 
closes #88 
Adds Option fo query Global-Github or just the `Eddiehub`-Organization
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/89"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add toggle for global query

package-lock.json, src/routes/index.svelte
Used header tag instead of div tag around title , toggle , and search bar to  improve semantic of page
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/112"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> used header instead of div tag

src/routes/index.svelte
As Suggested I have changed labels. If find it valid than please merge it to min branch. Thanks.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
resolve #99
=> changed the label from 'Organization' to 'EddieHub' and 'Globle' to 'Github'

package-lock.json, src/routes/index.svelte
Closes #103
replaced div tag with the main tag around issues listing from src/routes/index.svelte
before:
After:
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/120"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix:[OTHER] Use main tag instead of div tag #103

package.json
add MIT-License to the license-prop of the package.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/122"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add MIT-License to license-prop

.github/workflows/build.yml, package.json
closes #40
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ci: add build validation

README.md
I have modified the 3rd line from the installation steps as suggested from **cd linkfree** to **cd good-first-issue-finder** in the issue description.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated readme :modified the installation steps

README.md
Closes #131 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/132"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Updated Url. #131

package-lock.json, src/app.html, src/lib/components/footer.svelte
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/130"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added Discord and GitHub icons in footer instead of the text.

package-lock.json, src/lib/components/search.svelte
=> feat: add shortcut for search

README.md
Closes #127
- [x ] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/129"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Closes #127

.github/workflows/community.yml
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/146"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: community action on fork

README.md
Resolve partially #80
- [ x] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/172"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> doc : added license badge in README.md

src/routes/index.svelte
Fixes #174
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Typo on the header

package-lock.json, package.json, playwright.config.ts
closes #188
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Playwright for e2e tests

src/lib/components/footer.svelte
- Capitalize the `h` in the `GitHub` word.
- Update Discord/GitHub links to use EddieHub domains.
None yet.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/194"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: minor link improvements

.github/workflows/test.yml, .gitpod.yml, playwright.config.ts, tests/login.spec.ts
closes #191
based on #187 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/193"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Placeholder tests

kubernetes/deployment.yaml
closes #195 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/196"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: kubernetes secret name #195

package-lock.json, src/lib/components/footer.svelte, src/lib/components/package-version.svelte, src/lib/util/version.ts, src/routes/+layout.svelte, src/routes/+layout.ts, src/routes/api/version/+server.ts, svelte.config.js
closes #94
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/197"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Display Version Number

Dockerfile, package-lock.json, package.json
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/198"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: version

.github/workflows/build.yml, .github/workflows/test.yml, mdsvex.config.js, package-lock.json, package.json, src/lib/components/docs/layout.svelte, src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/docs/+page.md, static/prism.css, svelte.config.js, tailwind.config.cjs
closes #207
Hey @eddiejaoude, 
what do you think about having documentation inside the app as markdown files under the `/docs` route for example?
I like the idea of having everything inside the same place.
I've added a `/docs` route here as an example.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/208"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Documentation

package-lock.json, src/app.css, src/lib/components/header.svelte, src/lib/components/load-more.svelte, src/lib/components/profile-picture.svelte, src/routes/docs/+page.md, tests/login.spec.ts
closes #209
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/210"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Minor UI Tweaks

.github/workflows/kubescape.yml
closes #211 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/213"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create kubescape.yml file

package-lock.json, src/global.d.ts, src/lib/components/checkbox.svelte, src/lib/components/filter.svelte, src/routes/+page.svelte, src/routes/api/get-issues/+server.ts
closes #105 
Layout changes slightly
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/214"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Create Accessible Checkboxes

src/lib/components/footer.svelte, src/lib/components/header.svelte, src/lib/components/theme-switcher.svelte, src/routes/login/+page.svelte, tests/login.spec.ts
Added all the tests there were created for Login
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/218"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ADD: login tests added

.dockerignore
closes #230 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/232"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: added `.dockerignore` file

README.md
Closes #234 
Added how to upgrade node version documentation link using node website and command line.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/236"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Added node version update in readme file

src/lib/contents/docs-menu.ts, src/routes/docs/your-issues/+page.md
closes #205
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/248"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: add documentation for custom label

package-lock.json, tests/docs/introduction.spec.ts
- [X ] My change requires changes to the documentation.
=> Feat: Add of Correct Page Headers

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/docs.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/other.yml
closes #250 
Added custom forms for the Finder -
- General Feature Request
- Documentation issue
- Bug
- Other
- 🙋🏾🙋🏼‍Question
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: add custom issue forms for Finder

.gitignore, .gitpod.yml, histoire.config.ts, package-lock.json, package.json, src/histoire-setup.ts, src/stories/card.story.svelte, src/stories/footer.story.svelte, src/stories/issue-card.story.svelte, src/stories/label.story.svelte, src/stories/loader.story.svelte, src/stories/repo-header.story.svelte
Adds Histoire, an alternative to Storybook to the project
**either merge this or #240, but not both**
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/242"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Histoire

CONTRIBUTING.md
Closes #255  
Add spaces between "-" and text
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/256"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix space issue in contributing.md

README.md
The changes involve the addition of shields in the README.md file
=> shields added into README.md file

src/global.d.ts, src/routes/+page.svelte, src/routes/+page.ts, src/routes/api/get-issues/+server.ts, src/stories/issue-card.story.svelte
Closes #265. Fixes #263 
Added `archived:false` in the query strings
=> Fix the internal server on load more and implement archive filter in query

src/lib/constants.json, src/routes/+page.svelte, src/routes/+page.ts
While working on #265 I didn't realize there are 2 files where I was supposed to make the changes. So to fix this confusion in this PR I have made constants file to be used as module where required.
N/A
I tested this locally, it does not break anything this time 😅
=> Use the constant global state for the repeated variables

src/routes/+page.svelte
I have made changes to correct the instances of the word "serach" to "search" throughout the codebase. I have also double-checked the entire codebase to ensure that there are no other instances of this typo.
Please review the changes and let me know if there are any issues or if there are any other places that need to be fixed.
Fixes #273: Typo Fix - "search" instead of "serach"
Thank you,
#273: Typo Fix - "search" instead of "serach"
=> Fix typo: 'serach' to 'search'

README.md
Closes #80 
Discord badge was added into README.md
=> Discord badge was added into README.md #80

CONTRIBUTING.md
**The number 7 was repeated twice so i fixed it overall point is 12.**
=> Fixed the number repeating

src/routes/app/+page.svelte
closes #286 
Labels will not disappear when we don't get any results.
=> Fixed issue of filter when no results are found

README.md
Closes #288 
Wrote a note for .env file creation.
=> Updated installation guide in ReadMe

package-lock.json, package.json, src/lib/components/header.svelte, src/lib/data.ts, src/routes/+layout.server.ts, src/routes/+layout.svelte, src/routes/+layout.ts, src/routes/api/get-issues/+server.ts, src/routes/app/+page.svelte, src/routes/app/+page.ts
=> Migrate to Svelte-Query

package-lock.json, package.json, src/hooks.server.ts, src/routes/api/authentication/callback/+server.ts, src/routes/api/authentication/login/+server.ts, src/routes/api/authentication/logout/+server.ts, src/routes/api/get-issues/+server.ts
=> remove cookie dependency

package-lock.json, src/routes/app/+page.svelte
=> Display Labels when no result

package-lock.json, src/lib/components/profile-picture.svelte
=> Close Banner on Navigation

src/routes/+layout.svelte
Closes #212 
Currently there is bottom scroll bar on `/` route while, it doesn't appears on other routes such as `/docs` or `/login`.
=> Fixed bottom scrollbar issue on / route

src/lib/components/docs/menu-item.svelte, tests/login.spec.ts
=> change color of docs menu-item on hover

src/lib/components/filter.svelte, src/lib/components/modal.svelte, src/routes/app/+page.svelte
Closes #215
Video: 
https://user-images.githubusercontent.com/46050644/230729011-f3cb4b62-472f-4ed4-8354-18ce58d69d6f.mp4
=> Added filter modal

src/error.html
=> updated the error title and error subtitle

src/lib/components/footer.svelte
=> added Linkedin Link

CONTRIBUTING.md
Updated link to github docs as mentioned in issue https://github.com/EddieHubCommunity/good-first-issue-finder/issues/324
closes #324
=> Updated links to github Docs

package-lock.json, package.json, src/lib/components/checkbox.svelte, src/lib/components/filter.svelte, src/lib/components/modal.svelte, src/lib/stores/selected-labels.store.ts, src/routes/app/+page.svelte
=> Modal to Radix

README.md
- Add fork link in the installation steps.
None.
=> docs: add fork link in the installation steps

src/lib/components/modal.svelte, src/routes/+page.svelte
closes #342
Modified the color scheme of the page to look like
=> Fix for :  UI text color is light if browser's mode is set to dark mode #342

README.md, src/lib/components/checkbox.svelte, src/lib/components/header.svelte
Closes #361
I have fixed the typo in the function name and it is not breaking any functionality for me.
I have also updated readme to clarify to make a OAuth App and not a GitHub App.
I also removed a console.log statement.
=> fix typo in function name

package-lock.json, src/lib/components/index/github-card.svelte
closes #315 
Adjusted color contrast(changed to darkest shade of gray) of github-hover-effect for both the dark mode as well as for the light mode
=> Adjust color contrast for github-hover-effect

src/routes/+error.svelte
Minor typo fixed
Fixed a minor typo.
=> Update +error.svelte - fixed typo

package-lock.json
Updated the version of outdated vulnerable packages
Updated versions are saved in `package-lock.json`
=> Update vulnerable dependencies version

package-lock.json, src/lib/components/hamburger-menu/menu.svelte
- Mobile view nav bar spacing updated
- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.
=> Mobile nav updated

README.md
'upgrade your node version'
to
'Upgrade your node version'
=> fix: lowercase to uppercase

README.md
Hello:)
I have fixed the repo rater badge
=> Repo rater badge fix

README.md
Hello:)
I have update the preview image.
=> Updated Preview
